version: '3.9'

services:
  java_db:
    container_name: cat_db
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: codigo123
      POSTGRES_USER: postgres
      POSTGRES_DB: catvie
    volumes:
      - pgdata:/var/lib/postgresql/data

  spring_app:
    container_name: cat_spring
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - java_db
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  pgdata: {}
